### ISSUE TITLE
Show set bonuses in item tooltips

### ISSUE THREAD

**Issue by TurkeyTickle** [TurkeyTickle/mhw-builder#12]
Set bonuses should show in item tooltips. Number of set pieces required and the skill the grant should also be shown.

**Comment by neftalimich** [comment]
Hi, I've already done this, sorry for not informed you before, next time I'll let you know sooner.
Last question, where did you get the information of items(armors, weapons, etc)? I want to add gamma armors, but i don't know how did you get their id, or it is a simple consecutive number?

Regards :)
![sin titulo](https://user-images.githubusercontent.com/10821661/42065008-3b833274-7afe-11e8-9f4a-1886854dc3c4.png)

**Comment by TurkeyTickle** [comment]
No worries - I'll assign issues to myself if I've started on them or plan on starting on them soon, so feel free to work on any issue that isn't assigned to me. I invited you to become a collaborator on this repo so you can assign issues to yourself and submit PRs from your own branch. If you'd rather just keep working out of your fork instead that's totally fine too, I just figured it might be easier as a collaborator :)

The id is just a unique number for each data set. The important thing is just to not change the id of any items after they have been pushed to the master branch so any build links out in the wild don't get messed up. I pretty much just search whatever file I'm adding data to for the max id and increment from there when I add new items.

I'll close this issue out when I get your PR :)
