### ISSUE TITLE
"Non-Elemental Boost"

### ISSUE THREAD

**Issue by neftalimich** [TurkeyTickle/mhw-builder#41]
Attack doesn't increase when set this skill. This skill increases the base attack by 10%. calculation must change:

(BaseAttack + AgumentationAttack * WeaponModifier) * **1.1** + (ActiveAttack+PasiveAttack) * WeaponModifier

Example:
Diablos Shatterer II + Elementless Jewel: (1196 + 0 * 5.2) * 1.1 + (0+0) * 5.2  ≈ 1316
Diablos Shatterer II + AugmentationAttack x2 + Elementless Jewel + AttackBoost x7: (1196 + 10 * 5.2) * 1.1 + (21+0) * 5.2  ≈ 1482

Regards and thanks for all :)

**Comment by neftalimich** [comment]
Hi, its me again, I didn't wanna do a "pull request", since I do not know how much progress you have made these days, because i saw that you have many enhancement to make.

I cloned your repository, and I made these improvements:
- Added Elementless Boost Modifier
- Added Average Raw Attack
- Added Average Raw Attack Potential
- Added Tooltip in Mobile

You can check it in this page: 
https://neftalimich.github.io/mhw-builder-page/?#v1i95a1a2d58i1d94i63d94i104i147d52i193d12d12i289l3

![whatsapp image 2018-06-20 at 12 51 45](https://user-images.githubusercontent.com/10821661/41675992-da20c2a0-7489-11e8-99b2-64571ac0b989.jpeg)

regards

**Comment by TurkeyTickle** [comment]
Nice, those changes look great!

I've been pretty busy with work, so unfortunately the only work I've been able to do on this recently is some refactoring to allow localization. That work is in the develop branch and not quite ready to be merged into master. I'd definitely like to get your changes merged in if you're up for putting them into a pull request though.

By the way, it looks like you've also taken care of #19 which is awesome. My only nitpick is that it would be nice to hide the close button on the tooltip on non-mobile devices.

Again, awesome work!

**Comment by neftalimich** [comment]
Hi, I can't créate a pull request, I don't have permissions. Anyway, I forked https://github.com/neftalimich/mhw-builder-1

**Comment by TurkeyTickle** [comment]
You should be able to create a pull request from your fork.

https://help.github.com/articles/creating-a-pull-request-from-a-fork/
