### ISSUE TITLE
Get the slot-item origin of the decoration-slots

### ISSUE THREAD

**Issue by neftalimich** [TurkeyTickle/mhw-builder#44]
Hi, I'm doing an improvement in the details of the skills, but I don't know how to get the item.slot.ItemType to which the decoration.slot belongs, . Thanks in advance.
https://github.com/neftalimich/mhw-builder/commit/2910434ad2cd431cd5a1df42a7c2de3e74cd145a
![sin titulo](https://user-images.githubusercontent.com/10821661/41823805-a257c446-77cb-11e8-82fc-8bc7196a6f91.png)

**Comment by TurkeyTickle** [comment]
I need to refresh my memory on this. I'll get back to you shortly.

**Comment by TurkeyTickle** [comment]
DecorationModel has an itemId property, so you should be able to do something like this I think:

`const parentItem = _.find(equippedItems, item => item.id === decoration.itemId)`

**Comment by neftalimich** [comment]
Thank you very much, I found a different solution, I already have the improvements:
https://neftalimich.github.io/mhw-builder-page/?#v1ii31d12i77i104i147d54i191d54i226l3

**Comment by TurkeyTickle** [comment]
Very nice, looks like a good addition. Feel free to submit another PR.
