### ISSUE TITLE
Issue: parse tsv skills on weapons

### ISSUE THREAD

**Issue by neftalimich** [TurkeyTickle/mhw-builder#49]
it always happens with the last column when is parsed

- How must be:
![issue skills2](https://user-images.githubusercontent.com/10821661/42193243-0d49b5e4-7e33-11e8-8db0-a576fa0a6132.PNG)

- How is it:
![issue skills1](https://user-images.githubusercontent.com/10821661/42193240-09cf005e-7e33-11e8-8c06-483b3d124a9b.PNG)

- What did I do to solve it:

**weapons.tsv** (\t added)
![issue skills3](https://user-images.githubusercontent.com/10821661/42193287-54ee6cf0-7e33-11e8-8f05-4f831ffed518.PNG)

**skill.service.ts - addSetSkills**
![issue skills4](https://user-images.githubusercontent.com/10821661/42193306-7514de56-7e33-11e8-8e58-862835e46307.PNG)

Do you have any clue to solve it in a better way?
thanks in advance :)

**Comment by TurkeyTickle** [comment]
It looks like the problem is that your editor is saving the TSV with CR line endings. The parsing code for the armor and weapon TSVs expects the line endings to be LF. If you change your editor to save with LF line endings and save the file again I think it'll work.

**Comment by neftalimich** [comment]
Yes, the file has CRLF instead of LF. Thankyou so much.
