### ISSUE TITLE
Raw attack stats show "infinity" when a bowgun is selected

### ISSUE THREAD

**Issue by TurkeyTickle** [TurkeyTickle/mhw-builder#51]

**Comment by neftalimich** [comment]
weapon-modifier.json has a capital letter and weapons.tsv has a lower case:
HeavyBow**G**un ≠ HeavyBow**g**un
LightBow**G**un ≠ LightBow**g**un

**Comment by TurkeyTickle** [comment]
Ah, easy fix. Thanks for looking at at it.
