### ISSUE TITLE
Add detailed Light and Heavy Bowgun stats

### ISSUE THREAD

**Issue by TurkeyTickle** [TurkeyTickle/mhw-builder#6]
Deviation and ammo types data needs to be added, and they should be displayed in tooltips and the stat sheet.

**Comment by neftalimich** [comment]
**Back-end proposal**

- ammo-capacity.tsv
![mhw-builder-ammocapacity-1](https://user-images.githubusercontent.com/10821661/42293541-ab6411d4-7fa0-11e8-9d6f-87ef72207e53.png)

- ammo-capacity.model.ts
![mhw-builder-ammocapacity-2](https://user-images.githubusercontent.com/10821661/42293550-bb8cd122-7fa0-11e8-8438-003615017536.png)

- data.service.ts
![mhw-builder-ammocapacity-3](https://user-images.githubusercontent.com/10821661/42293554-bfac56a6-7fa0-11e8-99ca-53906f3c8db4.png)

- view example
I don't like it, I'm not good at designing u_U
It would be better in a tooltip, I'll need your help to do it.
![mhw-builder-ammocapacity-4](https://user-images.githubusercontent.com/10821661/42293577-f013575e-7fa0-11e8-8e69-813756795abb.png)

**Comment by TurkeyTickle** [comment]
I think the back end changes make sense, although I would refactor the ammoCapacities lookup into a separate function to avoid as much duplicate code as possible. If you want, go ahead and submit a PR with these changes and I'll merge them into a bowgun stats branch and see if I can come up with a better way to display the ammo stats.

**Comment by TurkeyTickle** [comment]
Thanks for submitting the back end work. I merged into the bowgunstats branch and made a first attempt at adding it to the item tooltip. Since there is a lot of ammo data to show, I think it's important for it to take up as little space as possible especially if we put it in a tooltip. So I used a smaller font size and only show ammo types that don't have a capacity of 0 for all levels. Let me know what you think, and feel free to pull the bowgunstats branch and tweak it if you want.

![ammo](https://user-images.githubusercontent.com/6629004/42364462-752fdf44-80b8-11e8-9558-d8a4af781c18.png)

**Comment by neftalimich** [comment]
Looks great, very very great. I found all the ammo information (Kulve Taroth included). In a couple of hours I'll upload the updated file.
I think it will be necessary to create a button for the mobile version that makes this tooltip appear.

**Comment by TurkeyTickle** [comment]
Yeah, I think it probably makes sense to have a button or something on the right side stats section that shows ammo info in a modal or a tooltip when touched like calculations. I'll play around with that some and see what I can come up with.

**Comment by neftalimich** [comment]
I like it so much ❤️ .  Yes I have already all ammo capacities information, I'm waiting for the merge into develop branch. I have also been thinking about adding buttons in the titles to hide the information (Attack, Defense, Skills, Ammo, Melodies, etc.) what do you think about that?

**Comment by TurkeyTickle** [comment]
Cool, I plan on merging to develop sometime today and to master shortly after. 

I was also thinking it might be useful to add some way to collapse the stat sections on the right side. I opened #53 where we can discuss and track that.
